FROM node:20-alpine AS build
WORKDIR /rlcc-assistant-client

COPY package*.json ./
RUN npm ci --legacy-peer-deps --no-audit --no-fund

COPY . .
RUN npm run build -- --configuration production

FROM nginx:1.27-alpine
COPY nginx.prod.conf /etc/nginx/conf.d/default.conf
COPY --from=build /rlcc-assistant-client/dist/rlcc-assistant-client/browser /usr/share/nginx/html

EXPOSE 80
